🛠 Ensure `yarn build` and `yarn test` work as expected (#143)
* Enable yarn run v1.9.4
$ yarn ganache && yarn compile && yarn rollup
$ ganache-cli --networkId ${npm_package_config_ganacheNetworkID} --verbose --gasLimit ${npm_package_config_ganacheGasLimit} --gasPrice ${npm_package_config_ganacheGasPrice} --port ${npm_package_config_ganachePort} --deterministic --account="${npm_package_config_unlockedAccount0},${npm_package_config_etherBalance}" --account="${npm_package_config_unlockedAccount1},${npm_package_config_etherBalance}" --account="${npm_package_config_unlockedAccount2},${npm_package_config_etherBalance}" &> /dev/null &
$ yarn wsrun build $PKG --fast-exit -r --stages --exclude-missing
$ wsrun build --fast-exit -r --stages --exclude-missing
@counterfactual/typescript-typings has no  build script, skipping missing
@counterfactual/dev-utils
 | [2K[1G[2m$ tsc -b[22m
@counterfactual/contracts
 | [2K[1G[2m$ yarn compile && yarn deploy[22m
 | [2K[1G[2m$ truffle compile && apply-registry build/contracts[22m
 | Processing artifacts in build/contracts...
 | Updated artifact AddressUtils.json to packages/contracts/build/contracts/AddressUtils.json
 | Updated artifact DelegateProxy.json to packages/contracts/build/contracts/DelegateProxy.json
 | Updated artifact MultiSend.json to packages/contracts/build/contracts/MultiSend.json
 | Updated artifact ERC20Basic.json to packages/contracts/build/contracts/ERC20Basic.json
 | Updated artifact ExampleTransfer.json to packages/contracts/build/contracts/ExampleTransfer.json
 | Updated artifact ERC20.json to packages/contracts/build/contracts/ERC20.json
 | Updated artifact ExampleCondition.json to packages/contracts/build/contracts/ExampleCondition.json
 | Updated artifact Echo.json to packages/contracts/build/contracts/Echo.json
 | Updated artifact Proxy.json to packages/contracts/build/contracts/Proxy.json
 | Updated artifact DolphinCoin.json to packages/contracts/build/contracts/DolphinCoin.json
 | Updated artifact ProxyFactory.json to packages/contracts/build/contracts/ProxyFactory.json
 | Updated artifact Migrations.json to packages/contracts/build/contracts/Migrations.json
 | Updated artifact TestCaller.json to packages/contracts/build/contracts/TestCaller.json
 | Updated artifact ETHBalanceRefundApp.json to packages/contracts/build/contracts/ETHBalanceRefundApp.json
 | Updated artifact SafeMath.json to packages/contracts/build/contracts/SafeMath.json
 | Updated artifact BasicToken.json to packages/contracts/build/contracts/BasicToken.json
 | Updated artifact Conditional.json to packages/contracts/build/contracts/Conditional.json
 | Updated artifact PaymentApp.json to packages/contracts/build/contracts/PaymentApp.json
 | Updated artifact Registry.json to packages/contracts/build/contracts/Registry.json
 | Updated artifact StaticCall.json to packages/contracts/build/contracts/StaticCall.json
 | Updated artifact Signatures.json to packages/contracts/build/contracts/Signatures.json
 | Updated artifact ConditionalTransaction.json to packages/contracts/build/contracts/ConditionalTransaction.json
 | Updated artifact VirtualAppAgreement.json to packages/contracts/build/contracts/VirtualAppAgreement.json
 | Updated artifact Transfer.json to packages/contracts/build/contracts/Transfer.json
 | Updated artifact MinimumViableMultisig.json to packages/contracts/build/contracts/MinimumViableMultisig.json
 | Updated artifact CountingApp.json to packages/contracts/build/contracts/CountingApp.json
 | Updated artifact StandardToken.json to packages/contracts/build/contracts/StandardToken.json
 | Updated artifact Nim.json to packages/contracts/build/contracts/Nim.json
 | Updated artifact NonceRegistry.json to packages/contracts/build/contracts/NonceRegistry.json
 | Updated artifact CommitRevealApp.json to packages/contracts/build/contracts/CommitRevealApp.json
 | Updated artifact TicTacToe.json to packages/contracts/build/contracts/TicTacToe.json
 | Updated artifact AppInstance.json to packages/contracts/build/contracts/AppInstance.json
 | Complete!
 | [2K[1G[2m$ yarn truffle:migrate-off-chain[22m
 | [2K[1G[2m$ rm -f networks/*.json && truffle migrate --network ganache[22m
 | Network up to date.
@counterfactual/machine
 | [2K[1G[2m$ tsc[22m
@counterfactual/cf.js
 | [2K[1G[2m$ tsc[22m
@counterfactual/wallet
 | [2K[1G[2m$ tsc[22m
 | packages/wallet/src/iframe/contracts.ts(12,25): error TS2307: Cannot find module '../../../contracts/networks/7777777.json'.
 | [2K[1G[34minfo[39m Visit [1mhttps://yarnpkg.com/en/docs/cli/run[22m for documentation about this command.
Stopping 5 active children
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. to pass in the root

* Enable jest to actually run tests for machine

* Lint in the appropriate way.

* Remove prettier since it's implicit inside tslint

* Use tsc and truffle compile for contracts

* Clean separation at contracts layer

* Use results array

* yarn clean && yarn build && yarn test works for machine

* rename to iframe-wallet-poc

* iframe wallet tests pass... not a good look for those tests

* Ensure yarn clean in all repos

* Misc. repo cleanups

* Rename counterfactual_logo to logo

* Better lint for cf.js

* Wallet up to the point where real addresses need to be put in

* Ethmo Works

* Update lerna

* Remove compile command from monorepo

* Better lerna commands

* Update root package.json and linting

* prettier

* Explicitly remove the prettier stuff, tslint does it by itself

* [WIP] Make cf-operation.spec.ts pass

* Rename store

* WIP making cf-operations test pass

* Remove unused line of code

* Mini refactor to ensure test-response-sink is simple

* Remove FIXME

* cf-operations test passes again

* All machine tests pass

* Wallet tests pass

* Update CI

* Update CI

* Simplify linting commands

* Update CI

* Update CI docker image to use updated yarn

* Update CI cache directories

* Version CI cache keys

* Run ganache in the background

* Rename ganache ci script